Repository arctern-io/arctern, pull requests merged in 2020-03, with the labels that each got.

#154 Add pod tolerations to Jenkins slave pods
  ci/jenkins/pod/arctern-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/arctern-gpu-version-ubuntu18.04-build-env-pod.yaml
Labels: enhancement

#162 Update .env file
  .env
Labels: bug

#164 Update build conda package document
  doc/Build-Conda-Package.md
  doc/compile-with-conda.md
  docker/build_env/cpu/Dockerfile
Labels: documentation

#178 Update install Arctern Spark with conda document
  ci/docker/conda-build.dockerfile
  doc/Build-Conda-Package.md
  doc/compile-with-conda.md
  doc/install-arctern-spark-with-conda.md
  doc/install-arctern-with-conda.md
  docker/build_env/cpu/Dockerfile
  docker/spark/cpu/Dockerfile
  docker/spark/cpu/arctern/install_arctern_spark.sh
  docker/spark/cpu/spark-defaults.conf
  docker/spark/cpu/zgis.yml
  docker/spark/gpu/Dockerfile
  docker/spark/gpu/arctern/install_arctern_spark.sh
  docker/spark/gpu/spark-defaults.conf
  docker/spark/gpu/zgis.yml
Labels: documentation

#179 Update doc/Build-Conda-Package.md
  doc/Build-Conda-Package.md
  doc/compile-with-conda.md
Labels: documentation

#185 Update arctern spark dockerfile
  doc/deploy-with-docker-compose.md
  docker/spark/cpu/Dockerfile
  docker/spark/gpu/Dockerfile
Labels: bug

#190 Update arctern spark dockerfile
  ci/docker/conda-build.dockerfile
  ci/docker/conda-cudagl-10.0-build.dockerfile
  doc/install-arctern-spark-with-conda.md
  docker/build_env/cpu/Dockerfile
  docker/build_env/gpu/Dockerfile
  docker/spark/cpu/Dockerfile
  docker/spark/gpu/Dockerfile
Labels: enhancement

#236 fix #232, return null if input is empty, for ST_HausdorffDistance
  cpp/src/gis/gdal/gis_functions.cpp
  cpp/unittest/gis/gis_functions_tests.cpp
  doc/How-to-determine-if-tow-geometries-are-approximately-equal.md
Labels: arctern-0.1.0, bug

#239 Add English version readme
  README.md
  README_CN.md
  doc/img/icon/arctern-black.png
  doc/img/icon/arctern-color.png
  doc/install_arctern_on_spark_cn.md
Labels: arctern-0.1.0, documentation

#215 Add Arctern Regression in Jenkins CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/docker-pod.yaml
  ci/jenkins/step/arcternSparkRegression.groovy
  ci/jenkins/step/buildArcternSparkImage.groovy
  ci/jenkins/step/condaBuild.groovy
  ci/scripts/conda/cpu/build.sh
  ci/scripts/conda/cpu/upload_package.sh
  ci/scripts/conda/gpu/build.sh
  ci/scripts/conda/gpu/upload_package.sh
  ci/scripts/run_spark_regression.sh
  conda/recipes/arctern-spark/meta.yaml
  conda/recipes/arctern/meta.yaml
  conda/recipes/libarctern/cpu/meta.yaml
  conda/recipes/libarctern/gpu/meta.yaml
  doc/deploy-with-docker-compose.md
  docker-compose.yaml
  docker/spark/cpu/base/Dockerfile
  docker/spark/cpu/runtime/Dockerfile
  docker/spark/cpu/runtime/arctern/install_arctern_spark.sh
  docker/spark/cpu/runtime/docker-compose.yml
  docker/spark/cpu/runtime/prebuildfs/libfs.sh
  docker/spark/cpu/runtime/prebuildfs/liblog.sh
  docker/spark/cpu/runtime/prebuildfs/libos.sh
  docker/spark/cpu/runtime/prebuildfs/libservice.sh
  docker/spark/cpu/runtime/prebuildfs/libvalidations.sh
  docker/spark/cpu/runtime/rootfs/entrypoint.sh
  docker/spark/cpu/runtime/rootfs/libspark.sh
  docker/spark/cpu/runtime/rootfs/postunpack.sh
  docker/spark/cpu/runtime/rootfs/run.sh
  docker/spark/cpu/runtime/rootfs/setup.sh
  docker/spark/cpu/runtime/spark-defaults.conf
  docker/spark/gpu/arctern/install_arctern_spark.sh
  docker/spark/gpu/base/Dockerfile
  docker/spark/gpu/runtime/Dockerfile
  docker/spark/gpu/runtime/arctern/install_arctern_spark.sh
  docker/spark/gpu/runtime/docker-compose.yml
  docker/spark/gpu/runtime/prebuildfs/libfs.sh
  docker/spark/gpu/runtime/prebuildfs/liblog.sh
  docker/spark/gpu/runtime/prebuildfs/libos.sh
  docker/spark/gpu/runtime/prebuildfs/libservice.sh
  docker/spark/gpu/runtime/prebuildfs/libvalidations.sh
  docker/spark/gpu/runtime/rootfs/entrypoint.sh
  docker/spark/gpu/runtime/rootfs/libspark.sh
  docker/spark/gpu/runtime/rootfs/postunpack.sh
  docker/spark/gpu/runtime/rootfs/run.sh
  docker/spark/gpu/runtime/rootfs/setup.sh
  docker/spark/gpu/runtime/spark-defaults.conf
  docker/test_env/docker-compose.yaml
  docker/test_env/spark/cpu/docker-compose.yml
  docker/test_env/spark/cpu/spark-defaults.conf
  docker/test_env/spark/gpu/docker-compose.yml
  docker/test_env/spark/gpu/spark-defaults.conf
Labels: arctern-0.1.0, feature

#242 merge docs
  doc/install.md
  doc/install_arctern_on_spark_cn.md
Labels: arctern-0.1.0, documentation

#244 Change branch to master
  ci/scripts/conda/cpu/upload_anaconda.sh
  ci/scripts/conda/gpu/upload_anaconda.sh
Labels: arctern-0.1.0, feature

#247 add curve/surface equality check cases
  tests/compare.py
Labels: arctern-0.1.0, feature

#246 fix #245, return true if both input are empty geometry for st_equal
  cpp/src/gis/gdal/gis_functions.cpp
  cpp/unittest/gis/gis_functions_tests.cpp
Labels: arctern-0.1.0, bug

#238 refactor utils
  cpp/src/utils/log.h
  cpp/src/utils/visibility.h
Labels: arctern-0.1.0, duplicate

#225 modify python setup.cfg
  python/setup.cfg
Labels: arctern-0.1.0, documentation

#249 Add Code coverage in Jenkins CI
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/scripts/coverage.sh
  ci/scripts/cpp_build.sh
  codecov.yaml
Labels: arctern-0.1.0, feature

#250 Add install_en and refine readme
  README.md
  doc/install_arctern_on_spark_cn.md
  doc/install_arctern_on_spark_en.md
Labels: arctern-0.1.0, documentation

#235 rename actern_pyspark wrapper function
  doc/How-to-determine-if-tow-geometries-are-approximately-equal.md
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/examples/gis/intersecion_gen.py
  spark/pyspark/examples/gis/point_gen.py
  spark/pyspark/examples/gis/spark_udf_ex.py
  spark/pyspark/examples/gis/st_intersection_ex.py
  spark/pyspark/examples/gis/st_point_ex.py
  tests/geo_types_test_reference.md
  tests/spark_test.py
Labels: arctern-0.1.0, feature

#251 add doc
  doc/error_standard.md
Labels: arctern-0.1.0, documentation

#255 waper pyspark render interface && render examples
  cpp/src/arrow/render_api.cpp
  cpp/src/arrow/render_api.h
  cpp/src/render/render_builder.h
  cpp/src/render/render_builder_impl.h
  python/arctern_gis/cython/arctern_gis_core_.pyx
  python/arctern_gis/cython/arctern_gis_core__.pxd
  python/arctern_gis/cython/render.h
  spark/pyspark/arctern_pyspark/__init__.py
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/arctern_pyspark/register.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
  spark/pyspark/examples/render/render_ex.py
Labels: arctern-0.1.0, enhancement, feature

#259 Add CPP and Python build workflow in Github Action
  .env
  .github/workflows/conda_build.yml
  .github/workflows/cpp.yml
  .github/workflows/python.yml
  ci/docker/linux-apt-python.dockerfile
  ci/docker/ubuntu18.04-cpp.dockerfile
  ci/scripts/pyspark_build.sh
  ci/scripts/python_build.sh
  ci/scripts/run_pylint.sh
  ci/scripts/run_pytest.sh
  ci/scripts/run_unittest.sh
  ci/yaml/conda_env_cpp.yml
  ci/yaml/conda_env_python.yml
  docker-compose.yaml
Labels: arctern-0.1.0, feature

#261 Remove arctern cpu version unittest in Jenkins CI
  .github/workflows/python.yml
  ci/jenkins/Jenkinsfile
Labels: arctern-0.1.0, feature

#266 Rename package
  .gitignore
  conda/recipes/arctern/meta.yaml
  doc/compile-with-conda.md
  doc/install_arctern_on_spark_cn.md
  doc/install_arctern_on_spark_en.md
  python/arctern/__init__.py
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/arctern/cython/gis.h
  python/arctern/cython/render.h
  python/arctern/util/__init__.py
  python/arctern/util/vega/__init__.py
  python/arctern/util/vega/choropleth_map/__init__.py
  python/arctern/util/vega/choropleth_map/choropleth_map.py
  python/arctern/util/vega/heat_map/__init__.py
  python/arctern/util/vega/heat_map/vega_heat_map.py
  python/arctern/util/vega/scatter_plot/__init__.py
  python/arctern/util/vega/scatter_plot/vega_circle_2d.py
  python/arctern/util/vega/scatter_plot/vega_scatter_plot.py
  python/arctern/util/vega/vega_node.py
  python/arctern_gis/cython/arctern_gis_core_.pyx
  python/setup.cfg
  python/setup.py
  python/tests/geo/geo_test.py
  python/tests/geo/render_test.py
  python/tests/vega/vega_test.py
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
  spark/pyspark/examples/render/render_ex.py
Labels: arctern-0.1.0, enhancement

#267 Render code coverage of vega and color
  cpp/src/arrow/render_api.cpp
  cpp/src/render/2d/choropleth_map/choropleth_map.cpp
  cpp/src/render/2d/choropleth_map/choropleth_map.h
  cpp/src/render/2d/general_2d.cpp
  cpp/src/render/2d/general_2d.h
  cpp/src/render/2d/heatmap/heatmap.cpp
  cpp/src/render/2d/heatmap/heatmap.h
  cpp/src/render/2d/heatmap/set_color.cpp
  cpp/src/render/2d/heatmap/set_color.h
  cpp/src/render/2d/scatter_plot/pointmap.cpp
  cpp/src/render/2d/scatter_plot/pointmap.h
  cpp/src/render/render_builder_impl.h
  cpp/src/render/utils/color/color_gradient.cpp
  cpp/src/render/utils/vega/vega.cpp
  cpp/src/render/utils/vega/vega.h
  cpp/src/render/utils/vega/vega_choropleth_map/vega_choropleth_map.cpp
  cpp/src/render/utils/vega/vega_choropleth_map/vega_choropleth_map.h
  cpp/src/render/utils/vega/vega_heatmap/vega_heatmap.cpp
  cpp/src/render/utils/vega/vega_heatmap/vega_heatmap.h
  cpp/src/render/utils/vega/vega_scatter_plot/vega_circle2d.cpp
  cpp/src/render/utils/vega/vega_scatter_plot/vega_circle2d.h
  cpp/src/render/utils/vega/vega_scatter_plot/vega_scatter_plot.h
  cpp/unittest/render/CMakeLists.txt
  cpp/unittest/render/choropleth_map_test.cpp
  cpp/unittest/render/coordinate_projection_test.cpp
  cpp/unittest/render/heatmap_test.cpp
  cpp/unittest/render/pointmap_test.cpp
  cpp/unittest/render/vega_test.cpp
  python/tests/vega/vega_example.txt
Labels: arctern-0.1.0, feature

#271 Fix container name conflict in Arctern Spark Docker compose
  ci/jenkins/step/arcternSparkRegression.groovy
Labels: bug

#276 add url hash of miniz_ep to accelerate download patch
  cpp/cmake/ThirdParty.cmake
  cpp/thirdparty/versions.txt
Labels: arctern-0.1.0, enhancement

#273 relative comparison for curve/surface
  tests/compare.py
Labels: arctern-0.1.0, enhancement

#283 Add codecov upload in Github Action
  .github/workflows/cpp.yml
  ci/jenkins/step/coverage.groovy
  ci/scripts/coverage.sh
Labels: arctern-0.1.0, enhancement

#286 Fix codecov upload bug
  .github/workflows/cpp.yml
  ci/jenkins/step/coverage.groovy
Labels: arctern-0.1.0, bug

#287 Fix cmake
  cpp/CMakeLists.txt
Labels: arctern-0.1.0, enhancement

#288 Fix delete arctern base images bug
  ci/jenkins/step/buildArcternSparkImage.groovy
Labels: arctern-0.1.0, bug

#280 add merge/split, and cuda support for st_length
  cpp/src/gis/api.h
  cpp/src/gis/cuda/functor/st_length.cu
  cpp/src/gis/cuda/gis_functions.cpp
  cpp/src/gis/gdal/type_scan.cpp
  cpp/src/gis/gdal/type_scan.h
  cpp/src/gis/gis_functions.cpp
  cpp/src/gis/type_scan.h
  cpp/unittest/gis/gdal/type_scan_tests.cpp
  cpp/unittest/gis/gis_functions_tests.cpp
Labels: arctern-0.1.0, cuda, enhancement

#298 cpp unittest fix
  cpp/unittest/gis/gis_functions_tests.cpp
Labels: arctern-0.1.0, bug, enhancement

#300 Set up a local Conda channel for installing the Arctern
  doc/scripts/arctern_dependencies.txt
  doc/scripts/download_dependencies.py
  doc/set-up-a-local-channel-for-installing-arctern.md
Labels: arctern-0.1.0, documentation

#306 Add ccache in Jenkins CI
  ci/jenkins/pod/arctern-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/arctern-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/step/build.groovy
  ci/scripts/check_ccache.sh
  ci/scripts/cpp_build.sh
  ci/scripts/update_ccache.sh
  cpp/CMakeLists.txt
  cpp/cmake/DefineOptions.cmake
Labels: arctern-0.1.0, feature

#307 Fix heat map unstable bug
  cpp/src/render/2d/heatmap/set_color.h
  doc/compile-with-conda.md
Labels: arctern-0.1.0, bug

#309 Rename Conda environment name
  ci/docker/conda-build.dockerfile
  ci/docker/conda-cudagl-10.0-build.dockerfile
  ci/jenkins/step/build.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/unittest.groovy
  ci/scripts/conda/cpu/build.sh
  ci/scripts/conda/gpu/build.sh
  doc/compile-with-conda.md
  docker/build_env/cpu/Dockerfile
  docker/build_env/cpu/build_cpu_env.yml
  docker/build_env/gpu/Dockerfile
  docker/build_env/gpu/build_gpu_env.yml
  tests/docs.md
  zgis.yml
Labels: arctern-0.1.0, enhancement

#310 Simplified render api
  cpp/src/arrow/render_api.cpp
  cpp/src/arrow/render_api.h
  cpp/src/render/2d/choropleth_map/choropleth_map.cpp
  cpp/src/render/render_builder.h
  cpp/src/render/render_builder_impl.h
  cpp/src/render/utils/vega/vega_choropleth_map/vega_choropleth_map.cpp
  cpp/src/render/utils/vega/vega_choropleth_map/vega_choropleth_map.h
  cpp/unittest/render/CMakeLists.txt
  cpp/unittest/render/choropleth_map_test.cpp
  cpp/unittest/render/coordinate_projection_test.cpp
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/arctern/cython/render.h
  python/arctern/util/vega/__init__.py
  python/arctern/util/vega/_vega_functions.py
  python/arctern/util/vega/choroplethmap/__init__.py
  python/arctern/util/vega/choroplethmap/vega_choroplethmap.py
  python/arctern/util/vega/heatmap/__init__.py
  python/arctern/util/vega/heatmap/vega_heatmap.py
  python/arctern/util/vega/pointmap/__init__.py
  python/arctern/util/vega/pointmap/vega_pointmap.py
  python/arctern/util/vega/pointmap/vega_scatter_plot.py
  python/tests/geo/render_test.py
  python/tests/vega/vega_example.txt
  python/tests/vega/vega_test.py
  spark/pyspark/arctern_pyspark/__init__.py
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
Labels: arctern-0.1.0, enhancement

#316 support exception threw by c++
  python/arctern/cython/arctern_core__.pxd
Labels: arctern-0.1.0, enhancement

#313 enable gpu support for st_envelope
  cpp/src/gis/cuda/common/gis_definitions.impl.h
  cpp/src/gis/cuda/functor/st_envelope.cu
  cpp/src/gis/cuda/wkb/wkb_tag.h
  cpp/src/gis/cuda/wkb/wkb_transforms.cpp
  cpp/src/gis/dispatch/dispatch.h
  cpp/src/gis/dispatch/dispatch.impl.h
  cpp/src/gis/dispatch/wkt_type_scanner.cpp
  cpp/src/gis/gdal/format_conversion.cpp
  cpp/src/gis/gdal/gis_functions.cpp
  cpp/src/gis/gis_functions.cpp
  cpp/src/utils/check_status.h
  cpp/unittest/gis/cuda/transforms_tests.cpp
Labels: arctern-0.1.0, cuda, enhancement

#318 alter bounding_box format in vega
  python/arctern/_wrapper_func.py
  python/arctern/util/_functions.py
  python/arctern/util/vega/_vega_functions.py
  python/arctern/util/vega/choroplethmap/vega_choroplethmap.py
  python/arctern/util/vega/heatmap/vega_heatmap.py
  python/arctern/util/vega/pointmap/vega_pointmap.py
  python/tests/geo/render_test.py
  python/tests/vega/vega_test.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
Labels: arctern-0.1.0, enhancement

#317 Update Arctern build environment docker images
  ci/scripts/check_ccache.sh
  ci/scripts/conda/cpu/upload_package.sh
  ci/scripts/conda/gpu/upload_package.sh
  docker/build_env/cpu/build_cpu_env.yml
  docker/build_env/gpu/build_gpu_env.yml
Labels: arctern-0.1.0, enhancement

#315 add draw map function python test
  ci/yaml/conda_env_python.yml
  python/tests/geo/render_test.py
  tests/expected/draw_map/choropleth_map.png
  tests/expected/draw_map/curve_z.png
  tests/expected/draw_map/heat_map.png
Labels: feature

#321 modify compile instruction doc
  doc/compile-with-conda.md
  doc/install_arctern_on_spark_cn.md
  doc/install_arctern_on_spark_en.md
  doc/set-up-a-local-channel-for-installing-arctern.md
Labels: arctern-0.1.0, documentation

#325 [skip ci] change docs
  doc/compile-with-conda.md
  doc/install_arctern_on_spark_cn.md
  doc/install_arctern_on_spark_en.md
  doc/set-up-a-local-channel-for-installing-arctern.md
Labels: arctern-0.1.0, documentation

#324 wrap function diff_png && modify precision
  python/arctern/util/_functions.py
  python/tests/geo/render_test.py
Labels: feature

#330 Agg map iter
  spark/pyspark/arctern_pyspark/__init__.py
  spark/pyspark/arctern_pyspark/gis_func.py
Labels: arctern-0.1.0, feature

#327 exception and error code
  cpp/src/common/error.h
  cpp/src/utils/log.h
Labels: arctern-0.1.0, enhancement, feature

#328 init gui/server code
  gui/server/.gitignore
  gui/server/README.md
  gui/server/app/__init__.py
  gui/server/app/account.py
  gui/server/app/common/config.py
  gui/server/app/common/spark.py
  gui/server/app/common/token.py
  gui/server/app/common/utils.py
  gui/server/app/nyctaxi/data.py
  gui/server/app/nyctaxi/service.py
  gui/server/app/service.py
  gui/server/config.ini
  gui/server/data/account.db
  gui/server/manage.py
  gui/server/requirements.txt
Labels: arctern-0.1.0, feature

#331 Pylint check and format python code
  .pylintrc
  python/arctern/_wrapper_func.py
  python/arctern/util/_functions.py
  python/arctern/util/vega/_vega_functions.py
  python/arctern/util/vega/choroplethmap/vega_choroplethmap.py
  python/arctern/util/vega/heatmap/vega_heatmap.py
  python/arctern/util/vega/pointmap/vega_pointmap.py
  python/tests/geo/render_test.py
  python/tests/vega/vega_test.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
Labels: arctern-0.1.0, enhancement

#335 Update ccache script file
  ci/scripts/check_ccache.sh
  ci/scripts/update_ccache.sh
Labels: enhancement

#337 fix Parameter order error
  python/arctern/util/_functions.py
  python/arctern/util/vega/_vega_functions.py
  python/tests/geo/render_test.py
Labels: bug

#336 enable gpu support for st_area, st_distance, st_within
  cpp/src/CMakeLists.txt
  cpp/src/gis/cuda/common/gis_definitions.cpp
  cpp/src/gis/cuda/functor/st_area.cu
  cpp/src/gis/cuda/wkb/wkb_transforms.cpp
  cpp/src/gis/dispatch/dispatch.h
  cpp/src/gis/dispatch/dispatch.impl.h
  cpp/src/gis/dispatch/type_scanner.cpp
  cpp/src/gis/dispatch/type_scanner.h
  cpp/src/gis/dispatch/wkt_type_scanner.cpp
  cpp/src/gis/dispatch/wkt_type_scanner.h
  cpp/src/gis/gis_functions.cpp
  cpp/unittest/gis/cuda/CMakeLists.txt
  cpp/unittest/gis/cuda/arrow_conversion_tests.cpp
  cpp/unittest/gis/cuda/functor_area_tests.cpp
  cpp/unittest/gis/cuda/functor_distance_tests.cpp
  cpp/unittest/gis/cuda/functor_envelope_tests.cpp
  cpp/unittest/gis/cuda/functor_length_tests.cpp
  cpp/unittest/gis/cuda/functor_point_tests.cpp
  cpp/unittest/gis/cuda/functor_within_tests.cpp
  cpp/unittest/gis/cuda/test_common/geometry_factory.h
  cpp/unittest/gis/cuda/test_common/test_common.cpp
  cpp/unittest/gis/cuda/transforms_tests.cpp
  cpp/unittest/gis/gdal/type_scan_tests.cpp
  cpp/unittest/gis/test_common/transforms.h
Labels: arctern-0.1.0, cuda, feature

#338 fix #326 incorrect data entry types on building vega
  python/arctern/util/vega/choroplethmap/vega_choroplethmap.py
  python/arctern/util/vega/heatmap/vega_heatmap.py
  python/arctern/util/vega/pointmap/vega_pointmap.py
Labels: arctern-0.1.0, bug

#341 fix #329 pointmap is always white in gpu version
  cpp/src/render/2d/scatter_plot/pointmap.cpp
  cpp/src/render/utils/color/color.cpp
  cpp/unittest/render/CMakeLists.txt
Labels: arctern-0.1.0, bug

#344 Improve cython
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/setup.py
Labels: arctern-0.1.0, enhancement

#340 Update code example in readme and readme_cn
  README.md
  README_CN.md
Labels: arctern-0.1.0, documentation

#348 gui/server test framework
  .gitignore
  gui/server/app/account.py
  gui/server/app/nyctaxi/data.py
  gui/server/app/service.py
  gui/server/tests/conftest.py
  gui/server/tests/test_account.py
Labels: arctern-0.1.0, enhancement

#349 Limit the resources of publish docker container
  ci/jenkins/pod/docker-pod.yaml
Labels: arctern-0.1.0, enhancement

#347 weighted pointmap with multiple color and multiple point size
  cpp/src/arrow/render_api.cpp
  cpp/src/arrow/render_api.h
  cpp/src/render/2d/scatter_plot/weighted_pointmap.cpp
  cpp/src/render/2d/scatter_plot/weighted_pointmap.h
  cpp/src/render/render_builder.h
  cpp/src/render/render_builder_impl.h
  cpp/src/render/utils/color/color.cpp
  cpp/src/render/utils/color/color.h
  cpp/src/render/utils/vega/vega_scatter_plot/vega_pointmap.cpp
  cpp/src/render/utils/vega/vega_scatter_plot/vega_scatter_plot.h
  cpp/src/render/utils/vega/vega_scatter_plot/vega_weighted_pointmap.cpp
  cpp/src/render/utils/vega/vega_scatter_plot/vega_weighted_pointmap.h
  cpp/unittest/render/weighted_pointmap_test.cpp
  python/tests/vega/vega_example.txt
Labels: arctern-0.1.0, feature

#350 Using wkb data inside render
  cpp/src/arrow/render_api.cpp
  cpp/src/arrow/render_api.h
  cpp/src/render/2d/choropleth_map/choropleth_map.cpp
  cpp/src/render/2d/choropleth_map/choropleth_map.h
  cpp/src/render/render_builder.h
  cpp/src/render/render_builder_impl.h
  cpp/unittest/render/choropleth_map_test.cpp
  cpp/unittest/render/coordinate_projection_test.cpp
  cpp/unittest/render/heatmap_test.cpp
  cpp/unittest/render/pointmap_test.cpp
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/arctern/cython/render.h
  python/tests/geo/render_test.py
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
  tests/expected/draw_map/test_choropleth_map1.png
  tests/expected/draw_map/test_choropleth_map2.png
  tests/expected/draw_map/test_choropleth_map3.png
  tests/expected/draw_map/test_curve_z1.png
  tests/expected/draw_map/test_curve_z2.png
  tests/expected/draw_map/test_curve_z3.png
  tests/expected/draw_map/test_heat_map1.png
  tests/expected/draw_map/test_heat_map2.png
  tests/expected/draw_map/test_heat_map3.png
Labels: arctern-0.1.0, enhancement

#351 wrapper weighted pointmap python api
  cpp/src/arrow/render_api.h
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/arctern/cython/render.h
  python/arctern/util/_functions.py
  python/arctern/util/vega/_vega_functions.py
  python/arctern/util/vega/pointmap/vega_weighted_pointmap.py
  python/tests/geo/render_test.py
  python/tests/vega/vega_test.py
  tests/expected/draw_map/choropleth_map.png
  tests/expected/draw_map/curve_z.png
  tests/expected/draw_map/heat_map.png
Labels: arctern-0.1.0, feature

#355 Server ljq
  gui/server/app/common/token.py
  gui/server/app/nyctaxi/data.py
  gui/server/app/service.py
  gui/server/config.ini
  gui/server/tests/__init__.py
  gui/server/tests/conftest.py
  gui/server/tests/test_account.py
  gui/server/tests/test_service.py
  gui/server/tests/test_spark.py
Labels: arctern-0.1.0, enhancement

#357 add png diff tests
  .gitignore
  tests/data/0_10000_nyc_taxi_and_building.csv
  tests/draw_map/choropleth_map_nyc_1.png
  tests/draw_map/choropleth_map_nyc_10.png
  tests/draw_map/choropleth_map_nyc_11.png
  tests/draw_map/choropleth_map_nyc_12.png
  tests/draw_map/choropleth_map_nyc_13.png
  tests/draw_map/choropleth_map_nyc_14.png
  tests/draw_map/choropleth_map_nyc_15.png
  tests/draw_map/choropleth_map_nyc_16.png
  tests/draw_map/choropleth_map_nyc_17.png
  tests/draw_map/choropleth_map_nyc_18.png
  tests/draw_map/choropleth_map_nyc_19.png
  tests/draw_map/choropleth_map_nyc_2.png
  tests/draw_map/choropleth_map_nyc_3.png
  tests/draw_map/choropleth_map_nyc_4.png
  tests/draw_map/choropleth_map_nyc_5.png
  tests/draw_map/choropleth_map_nyc_6.png
  tests/draw_map/choropleth_map_nyc_7.png
  tests/draw_map/choropleth_map_nyc_8.png
  tests/draw_map/choropleth_map_nyc_9.png
  tests/draw_map/heat_map_nyc_1.png
  tests/draw_map/heat_map_nyc_2.png
  tests/draw_map/heat_map_nyc_3.png
  tests/draw_map/heat_map_nyc_4.png
  tests/draw_map/heat_map_nyc_5.png
  tests/draw_map/point_map_nyc_1.png
  tests/draw_map/point_map_nyc_2.png
  tests/draw_map/point_map_nyc_3.png
  tests/draw_map/point_map_nyc_4.png
  tests/draw_map/point_map_nyc_5.png
  tests/draw_map/point_map_nyc_6.png
  tests/draw_map_test.py
Labels: arctern-0.1.0, feature

#359 Server ljq
  gui/server/tests/test_service.py
Labels: arctern-0.1.0, enhancement

#354 use wkb in weighted pointmap
  cpp/src/arrow/render_api.cpp
  cpp/src/render/2d/scatter_plot/weighted_pointmap.cpp
  cpp/src/render/2d/scatter_plot/weighted_pointmap.h
  cpp/src/render/render_builder.h
  cpp/src/render/render_builder_impl.h
  cpp/src/render/utils/vega/vega_scatter_plot/vega_weighted_pointmap.cpp
  cpp/src/render/utils/vega/vega_scatter_plot/vega_weighted_pointmap.h
  cpp/unittest/render/CMakeLists.txt
  cpp/unittest/render/vega_test.cpp
  cpp/unittest/render/weighted_pointmap_test.cpp
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/tests/geo/render_test.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
Labels: arctern-0.1.0, feature

#364 fix #345 wrong choroplethmap when png size is small
  cpp/src/render/render_builder_impl.h
  cpp/unittest/render/coordinate_projection_test.cpp
Labels: arctern-0.1.0, bug

#363 #360 Add CentOS version of Arctern Spark regression
  ci/jenkins/Jenkinsfile
Labels: arctern-0.1.0, feature

#366 Server ljq
  .gitignore
  gui/server/data/0_5M_nyc_taxi_and_building.csv
Labels: arctern-0.1.0, feature

#369 add func WkbToWkt
  cpp/src/arrow/render_api.cpp
  cpp/src/arrow/render_api.h
  cpp/src/render/render_builder_impl.h
  cpp/unittest/render/coordinate_projection_test.cpp
  cpp/unittest/render/heatmap_test.cpp
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/arctern/cython/render.h
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
Labels: arctern-0.1.0, feature

#367 weighted pointmap, done
  cpp/src/render/2d/choropleth_map/choropleth_map.cpp
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/tests/geo/render_test.py
  spark/pyspark/arctern_pyspark/render_func.py
  spark/pyspark/examples/render/nyc_taxi.py
Labels: arctern-0.1.0, feature

#372 Refactor Jenkins CI workflow
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/arcternSparkRegression.groovy
  ci/jenkins/step/buildArcternSparkImage.groovy
Labels: arctern-0.1.0, enhancement

#375 add new draw_map function test
  tests/draw_map/choropleth_map_nyc_1.png
  tests/draw_map/choropleth_map_nyc_10.png
  tests/draw_map/choropleth_map_nyc_11.png
  tests/draw_map/choropleth_map_nyc_12.png
  tests/draw_map/choropleth_map_nyc_13.png
  tests/draw_map/choropleth_map_nyc_14.png
  tests/draw_map/choropleth_map_nyc_15.png
  tests/draw_map/choropleth_map_nyc_16.png
  tests/draw_map/choropleth_map_nyc_17.png
  tests/draw_map/choropleth_map_nyc_18.png
  tests/draw_map/choropleth_map_nyc_19.png
  tests/draw_map/choropleth_map_nyc_2.png
  tests/draw_map/choropleth_map_nyc_3.png
  tests/draw_map/choropleth_map_nyc_4.png
  tests/draw_map/choropleth_map_nyc_5.png
  tests/draw_map/choropleth_map_nyc_6.png
  tests/draw_map/choropleth_map_nyc_7.png
  tests/draw_map/choropleth_map_nyc_8.png
  tests/draw_map/choropleth_map_nyc_9.png
  tests/draw_map/heat_map_nyc_1.png
  tests/draw_map/heat_map_nyc_2.png
  tests/draw_map/heat_map_nyc_3.png
  tests/draw_map/heat_map_nyc_4.png
  tests/draw_map/heat_map_nyc_5.png
  tests/draw_map/point_map_nyc_1.png
  tests/draw_map/point_map_nyc_2.png
  tests/draw_map/point_map_nyc_3.png
  tests/draw_map/point_map_nyc_4.png
  tests/draw_map/point_map_nyc_6.png
  tests/draw_map/weighted_point_map_nyc_1_1.png
  tests/draw_map/weighted_point_map_nyc_1_2.png
  tests/draw_map/weighted_point_map_nyc_1_3.png
  tests/draw_map/weighted_point_map_nyc_1_4.png
  tests/draw_map/weighted_point_map_nyc_1_5.png
  tests/draw_map/weighted_point_map_nyc_2_1.png
  tests/draw_map/weighted_point_map_nyc_2_2.png
  tests/draw_map/weighted_point_map_nyc_2_3.png
  tests/draw_map/weighted_point_map_nyc_2_4.png
  tests/draw_map/weighted_point_map_nyc_2_5.png
  tests/draw_map/weighted_point_map_nyc_3_1.png
  tests/draw_map/weighted_point_map_nyc_3_2.png
  tests/draw_map/weighted_point_map_nyc_3_3.png
  tests/draw_map/weighted_point_map_nyc_3_4.png
  tests/draw_map/weighted_point_map_nyc_3_5.png
  tests/draw_map/weighted_point_map_nyc_4_1.png
  tests/draw_map/weighted_point_map_nyc_4_2.png
  tests/draw_map/weighted_point_map_nyc_4_3.png
  tests/draw_map/weighted_point_map_nyc_4_4.png
  tests/draw_map/weighted_point_map_nyc_4_5.png
  tests/draw_map_test.py
Labels: arctern-0.1.0, feature

#374 add Projection api
  cpp/src/arrow/render_api.cpp
  cpp/src/arrow/render_api.h
  cpp/src/render/render_builder.h
  cpp/src/render/render_builder_impl.h
  cpp/unittest/render/coordinate_projection_test.cpp
  python/arctern/_wrapper_func.py
  python/arctern/cython/arctern_core_.pyx
  python/arctern/cython/arctern_core__.pxd
  python/arctern/cython/render.h
  python/tests/geo/render_test.py
  spark/pyspark/arctern_pyspark/_wrapper_func.py
  spark/pyspark/arctern_pyspark/render_func.py
Labels: arctern-0.1.0, bug, feature

#383 test for restful api
  gui/server/config.ini
  gui/server/tests/client/__init__.py
  gui/server/tests/client/conftest.py
  gui/server/tests/client/test_account.py
  gui/server/tests/client/test_service.py
  gui/server/tests/client/test_spark.py
  gui/server/tests/restful/__init__.py
  gui/server/tests/restful/conftest.py
  gui/server/tests/restful/requirements.txt
  gui/server/tests/restful/test_account.py
  gui/server/tests/restful/test_service.py
Labels: arctern-0.1.0, enhancement

#382 Set the imagePullPolicy of the Jenkins slave container to IfNotPresent(default)
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/arctern-cpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/pod/arctern-gpu-version-ubuntu18.04-build-env-pod.yaml
  ci/jenkins/step/arcternSparkRegression.groovy
  ci/jenkins/step/build.groovy
  ci/jenkins/step/buildArcternSparkImage.groovy
  ci/jenkins/step/condaBuild.groovy
  ci/jenkins/step/coverage.groovy
  ci/jenkins/step/unittest.groovy
Labels: arctern-0.1.0, enhancement

#385 Imporve gui
  gui/server/app/common/config.py
  gui/server/app/common/spark.py
  gui/server/app/nyctaxi/data.py
  gui/server/app/service.py
  gui/server/config.ini
Labels: arctern-0.1.0, enhancement

#392 fix image upside down error
  spark/pyspark/arctern_pyspark/render_func.py
Labels: arctern-0.1.0, bug

#395 gui/server add load api
  gui/server/README.md
  gui/server/app/common/db.py
  gui/server/app/common/spark.py
  gui/server/app/service.py
  gui/server/config.ini
  gui/server/db.json
  gui/server/manage.py
Labels: arctern-0.1.0, enhancement, feature

#390 Fix storke width ruler is not enable
  cpp/src/render/2d/scatter_plot/weighted_pointmap.cpp
  cpp/src/render/2d/scatter_plot/weighted_pointmap.h
Labels: arctern-0.1.0, bug

#396 Refactor CI workflow
  ci/jenkins/Jenkinsfile
Labels: arctern-0.1.0, enhancement

#397 gui/server weighted_pointmap supported
  gui/server/README.md
  gui/server/app/common/db.py
  gui/server/app/common/spark.py
  gui/server/app/service.py
Labels: arctern-0.1.0, enhancement, feature

#405 Update the selected conda environment
  conda/recipes/libarctern/cpu/meta.yaml
  conda/recipes/libarctern/gpu/meta.yaml
  docker/test_env/spark/cpu/docker-stack.yml
Labels: arctern-0.1.0, enhancement

#407 [skip ci] load json config from command line
  gui/server/app/common/config.py
  gui/server/app/common/db.py
  gui/server/app/common/spark.py
  gui/server/app/nyctaxi/data.py
  gui/server/app/service.py
  gui/server/config.ini
  gui/server/manage.py
  gui/server/tests/client/__init__.py
  gui/server/tests/client/conftest.py
  gui/server/tests/client/test_account.py
  gui/server/tests/client/test_service.py
  gui/server/tests/client/test_spark.py
  gui/server/tests/restful/conftest.py
  gui/server/tests/restful/test_service.py
Labels: /gui/server, arctern-0.1.0, enhancement

#411 return None when render get empty dataframe
  spark/pyspark/arctern_pyspark/render_func.py
Labels: arctern-0.1.0, bug

#415 [skip ci] fix some bug of gui/server with standalone spark cluster
  gui/server/app/common/spark.py
  gui/server/app/service.py
  gui/server/db.json
  gui/server/requirements.txt
  gui/server/tests/restful/requirements.txt
Labels: /gui/server, arctern-0.1.0, enhancement, feature
