Repository arctern-io/arctern, pull requests merged in 2020-02, with the labels that each got.

#39 Czs agg merge
  cpp/src/gis/api.h
  cpp/src/gis/cpu/gdal_impl.cpp
  cpp/unittest/gis/cpp/geometry_test.cpp
  python/setup.cfg
  python/test/geo/geo_test.py
  python/zilliz_gis/cython/gis.h
  python/zilliz_gis/cython/zilliz_gis_core_.pyx
  python/zilliz_gis/cython/zilliz_gis_core__.pxd
Labels: feature

#42 Update build environment Dockerfile
  cpp/src/CMakeLists.txt
  docker/build_env/cpu/Dockerfile
  docker/build_env/cpu/docker-entrypoint.sh
  docker/build_env/cpu/zgis.yml
  docker/build_env/gpu/Dockerfile
  docker/build_env/gpu/docker-entrypoint.sh
  docker/build_env/gpu/zgis.yml
Labels: enhancement

#48 Add Jenkins CI for GIS
  ci/jenkins/Jenkinsfile
  ci/jenkins/pod/gis-cpu-version-ubuntu16.04-build-env-pod.yaml
  ci/jenkins/pod/gis-gpu-version-ubuntu16.04-build-env-pod.yaml
Labels: feature

#52 Add build stage in Jenkins CI
  build.sh
  ci/jenkins/Jenkinsfile
  ci/jenkins/step/build.groovy
  ci/scripts/cpp_build.sh
  ci/scripts/python_build.sh
  cpp/CMakeLists.txt
  cpp/scripts/gis_env.sh.template
  doc/compile-with-conda.md
  gis_with_conda.md
  python/build.sh
  python/setup.cfg
Labels: feature

#60 Add Cpplint & Clang-format & Clang-tidy for GIS
  .clang-format
  .clang-tidy
  .clang-tidy-ignore
  ci/jenkins/pod/gis-cpu-version-ubuntu16.04-build-env-pod.yaml
  ci/jenkins/pod/gis-gpu-version-ubuntu16.04-build-env-pod.yaml
  ci/scripts/cpp_build.sh
  cpp/CMakeLists.txt
  cpp/build-support/cpplint.py
  cpp/build-support/lint_exclusions.txt
  cpp/build-support/lintutils.py
  cpp/build-support/run_clang_format.py
  cpp/build-support/run_clang_tidy.py
  cpp/build-support/run_cpplint.py
  cpp/cmake/FindClangTools.cmake
  docker/build_env/cpu/Dockerfile
  docker/build_env/gpu/Dockerfile
Labels: feature

#65 Add pylint for GIS
  .pylintrc
  ci/scripts/run_pylint.sh
  cpp/build-support/cpplint.py
  cpp/build-support/run_cpplint.py
  docker/build_env/cpu/zgis.yml
  docker/build_env/gpu/zgis.yml
  zgis.yml
Labels: feature

#78 Cpplint attent copyright information
  cpp/build-support/run_cpplint.py
Labels: enhancement

#85 Change gpu version base docker image
  docker/build_env/cpu/zgis.yml
  docker/build_env/gpu/Dockerfile
  docker/build_env/gpu/zgis.yml
Labels: enhancement

#87 Add Pytest in Jenkins CI
  ci/jenkins/step/unittest.groovy
  ci/scripts/run_pytest.sh
  python/pytest.ini
  python/tests/geo/geo_test.py
  python/tests/geo/render_test.py
  python/tests/vega/vega_example.txt
  python/tests/vega/vega_test.py
Labels: feature

#118 update deploy-with-docker-compose.md
  doc/deploy-with-docker-compose.md
Labels: documentation

#121 Open check cpplint & clang-format & pylint operation
  ci/jenkins/step/build.groovy
  ci/scripts/cpp_build.sh
  ci/scripts/run_pylint.sh
  docker/spark/cpu/Dockerfile
  docker/spark/gpu/Dockerfile
Labels: feature
